// frontend/src/components/modals/GroupModal.tsx
import { Dialog } from "@headlessui/react";
import { ExclamationTriangleIcon } from "@heroicons/react/20/solid";
import Modal from "./Modal";
import useGroupModal from "../../stores/modals/useGroupModal";

const GroupModal = () => {
  const { isOpen, props, setOpen } = useGroupModal();

  return (
    <Modal show={isOpen} onClose={() => setOpen(false)} width="medium">
      <div className="sm:flex sm:items-start w-full">
        <div className="mt-3 text-center sm:mt-0 sm:text-left w-full">
          <Dialog.Title
            as="h3"
            className="text-lg font-medium leading-6 text-gray-900"
          >
            Add Group
          </Dialog.Title>

          <div className="mt-2 w-full">
            <input
              type="text"
              id="groupName"
              name="groupName"
              className="input w-full"
              placeholder="Name"
            />
            <textarea
              rows={4}
              name="groupDescription"
              id="groupDescription"
              className="block w-full input mt-4"
              placeholder="Description (optional)"
              defaultValue={""}
            />
          </div>
        </div>
      </div>

      <div className="mt-5 sm:mt-4 sm:flex sm:flex-row-reverse">
        <button
          type="button"
          className="btn btn-primary w-full sm:ml-3 sm:w-auto"
          onClick={() => {
            if (props.onSave) {
              props.onSave();
            }
            setOpen(false);
          }}
          tabIndex={2}
        >
          Save
        </button>
        <button
          type="button"
          className="btn mt-4 w-full sm:mt-0 sm:w-auto sm:text-sm"
          onClick={() => {
            setOpen(false);
          }}
          autoFocus
          tabIndex={1}
        >
          Cancel
        </button>
      </div>
    </Modal>
  );
};

export default GroupModal;

// frontend/src/lib/modals/GroupModal.svelte
<script lang="ts">
    import EmojiChooser from "../EmojiChooser.svelte";
    import Modal from "./Modal.svelte";

    export let isOpen: boolean = false;
    export let name: string = "";
    export let description: string = "";
    export let selectedEmoji: string = "❓";
    export let onClose: () => void;
    export let onSave: (emoji: string, name: string, description?: string) => void;
    export let mode: "Add" | "Edit" = "Add";

    let nameElement: HTMLInputElement;

    const onShow = () => {
        if (nameElement) {
            nameElement.focus();
        }
    };
</script>

<Modal
    {isOpen}
    {onShow}
    title={mode + " Group"}
    buttons={[
        {
            content: "Save",
            onClick: () => {
                if (onSave) {
                    onSave(selectedEmoji, name, description);
                }
            },
            classes: "btn-primary",
        },
        {
            content: "Cancel",
            onClick: () => {
                if (onClose) {
                    onClose();
                }
            },
        },
    ]}
    {onClose}>
    <div class="flex">
        <EmojiChooser
            selected={selectedEmoji}
            classes="mr-2"
            onChange={(emoji) => {
                selectedEmoji = emoji;
            }} />
        <input
            bind:this={nameElement}
            bind:value={name}
            type="text"
            placeholder="Group name"
            class="input input-bordered grow" />
    </div>
    <textarea
        class="textarea textarea-bordered w-full mt-2"
        rows="2"
        placeholder="Description (optional)"
        bind:value={description} />
</Modal>
